# Main properties
spring:
  application:
    name: eru
  jpa:
    database: default
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

# Logging database
logging:
  file: ${project.directory}/logs/eru.log
  level.org.springframework.web: INFO
  level.org.hibernate: INFO
  level.com.eru: INFO