spring:
  application:
    name: eru
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  datasource:
    url: jdbc:mysql://localhost:3306/eru?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: eru
    password: 951753
logging:
  file: ${project.directory}/logs/eru.log
  level.org.springframework.web: INFO
  level.org.hibernate: INFO
  level.com.eru: INFO